name: pymarc_dedupe
services:
  dev_db:
    type: postgres:16
    portforward: 5433
  test_db:
    type: postgres:16
    portforward: 5434

# DATABASE_URL=postgresql://postgres@localhost:5433/database python
# import os
# import psycopg2
# import dj_database_url
# db_conf = dj_database_url.config()
# write_con = psycopg2.connect(
#         database=db_conf["NAME"],
#         user=db_conf["USER"],
#         password=db_conf["PASSWORD"],
#         host=db_conf["HOST"],
#         port=db_conf["PORT"]
#     )
# os.environ.get('DATABASE_URL')
