[default]
name = ""

[development]
name = "developing"
db_name = "database"
db_user = "postgres"
db_host = "localhost"
db_port = 5433

[local_test]
name = "testing"
db_name = "database"
db_user = "postgres"
db_host = "localhost"
db_port = 5434

[ci]
db_name = "database"
db_user = "postgres"
db_host = "localhost"
db_port = 5432

[staging]
name = "staging-ing"

[production]
name = "production-ing"
