version: 2.1
orbs:
  python: circleci/python@3.1.0

jobs:
  lint:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/testing.txt
      - run:
          name: 'python: ruff format'
          command: ruff format . --check
      - run:
          name: 'python: ruff check'
          command: ruff check .
      # Currently excluding checks for documentation - remove these disables once this is remediated
      - run:
          name: 'python: pylint'
          command: pylint src tests --disable=C0114,C0115,C0116
  tests:
    docker:
      - image: cimg/python:3.12
        environment:
          ENV_FOR_DYNACONF: 'ci'
      - image: cimg/postgres:16.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: database
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements/testing.txt
      - run:
          name: "Run tests and measure coverage"
          command: "coverage run --source=src -m pytest tests/ && coveralls"

workflows:
  ci: 
    jobs:
      - lint
      - tests
